-- schema.sql - SCRIPT COMPLETO DE ESTRUCTURA (Supabase/Postgres)

-- 1. Tabla: trabajador (Usuarios)
CREATE TABLE IF NOT EXISTS trabajador (
    idtrabajador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    usuario VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    acceso VARCHAR(50) DEFAULT 'Usuario',
    estado VARCHAR(20) DEFAULT 'activo'
);

-- 2. Tabla: categoria
CREATE TABLE IF NOT EXISTS categoria (
    idcategoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT
);

-- 3. Tabla: presentacion (Unidades, Cajas, etc)
CREATE TABLE IF NOT EXISTS presentacion (
    idpresentacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT
);

-- 4. Tabla: articulo (Productos)
CREATE TABLE IF NOT EXISTS articulo (
    idarticulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50),
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    stock INT DEFAULT 0,
    precio_venta DECIMAL(10, 2) DEFAULT 0.00,
    idcategoria BIGINT REFERENCES categoria(idcategoria),
    idpresentacion BIGINT REFERENCES presentacion(idpresentacion),
    imagen TEXT,
    estado VARCHAR(20) DEFAULT 'activo',
    tipo_venta VARCHAR(50),
    tiras_por_paquete INT,
    unidades_por_tira INT,
    contenido_desc VARCHAR(255),
    fecha_vencimiento DATE
);

-- 5. Tabla: cliente
CREATE TABLE IF NOT EXISTS cliente (
    idcliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255),
    telefono VARCHAR(20),
    email VARCHAR(100)
);

-- 6. Tabla: venta
CREATE TABLE IF NOT EXISTS venta (
    idventa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcliente BIGINT REFERENCES cliente(idcliente),
    idtrabajador BIGINT REFERENCES trabajador(idtrabajador),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total_venta DECIMAL(10, 2) DEFAULT 0.00,
    estado VARCHAR(20) DEFAULT 'completada'
);

-- 7. Tabla: detalle_venta (Para registrar los items de cada venta)
CREATE TABLE IF NOT EXISTS detalle_venta (
    iddetalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idventa BIGINT REFERENCES venta(idventa),
    idarticulo BIGINT REFERENCES articulo(idarticulo),
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL
);

-- 8. Tabla: proveedor
CREATE TABLE IF NOT EXISTS proveedor (
    idproveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    contacto VARCHAR(255),
    telefono VARCHAR(20),
    direccion TEXT
);

-- 9. Tabla: documents (Para RAG/Chatbot)
CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Búsqueda vectorial
CREATE INDEX IF NOT EXISTS documents_embedding_idx 
ON documents USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Función para búsqueda RAG
CREATE OR REPLACE FUNCTION search_documents(
    query_embedding vector(1536),
    similarity_threshold float,
    match_count int
)
RETURNS TABLE(id int, content text, similarity float, metadata jsonb)
LANGUAGE sql
AS $$
SELECT
    d.id,
    d.content,
    1 - (d.embedding <=> query_embedding) as similarity,
    d.metadata
FROM documents d
WHERE 1 - (d.embedding <=> query_embedding) > similarity_threshold
ORDER BY d.embedding <=> query_embedding
LIMIT match_count;
$$;
