-- Basededatos.sql - Script completo para Supabase (PostgreSQL)

-- 1. Tabla: trabajador (Usuarios)
CREATE TABLE IF NOT EXISTS trabajador (
    idtrabajador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    usuario VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    acceso VARCHAR(50) DEFAULT 'Usuario',
    estado VARCHAR(20) DEFAULT 'activo'
);

-- 2. Tabla: categoria
CREATE TABLE IF NOT EXISTS categoria (
    idcategoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT
);

-- 3. Tabla: presentacion (Unidades, Cajas, etc)
CREATE TABLE IF NOT EXISTS presentacion (
    idpresentacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT
);

-- 4. Tabla: articulo (Productos)
CREATE TABLE IF NOT EXISTS articulo (
    idarticulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50),
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    stock INT DEFAULT 0,
    precio_venta DECIMAL(10, 2) DEFAULT 0.00,
    idcategoria BIGINT REFERENCES categoria(idcategoria),
    idpresentacion BIGINT REFERENCES presentacion(idpresentacion),
    imagen TEXT,
    estado VARCHAR(20) DEFAULT 'activo',
    tipo_venta VARCHAR(50),
    tiras_por_paquete INT,
    unidades_por_tira INT,
    contenido_desc VARCHAR(255)
);

-- 5. Tabla: cliente
CREATE TABLE IF NOT EXISTS cliente (
    idcliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255),
    telefono VARCHAR(20),
    email VARCHAR(100)
);

-- 6. Tabla: venta
CREATE TABLE IF NOT EXISTS venta (
    idventa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcliente BIGINT REFERENCES cliente(idcliente),
    idtrabajador BIGINT REFERENCES trabajador(idtrabajador),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total_venta DECIMAL(10, 2) DEFAULT 0.00,
    estado VARCHAR(20) DEFAULT 'completada'
);

-- 7. Tabla: detalle_venta (Para registrar los items de cada venta)
CREATE TABLE IF NOT EXISTS detalle_venta (
    iddetalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idventa BIGINT REFERENCES venta(idventa),
    idarticulo BIGINT REFERENCES articulo(idarticulo),
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL
);

-- 8. Tabla: proveedor (Tiendas)
CREATE TABLE IF NOT EXISTS proveedor (
    idproveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    contacto VARCHAR(255),
    telefono VARCHAR(20),
    direccion TEXT
);

-- ==========================================
-- DATOS INICIALES Y DE PRUEBA
-- ==========================================

-- Usuario Administrador (Password: 'admin')
INSERT INTO trabajador (nombre, apellidos, usuario, password, acceso, estado)
VALUES 
('Admin', 'User', 'admin', 'scrypt:32768:8:1$w2KQd2aC7GZ2B8vj$9641773489e24803b98c39d89ccf277a83d0f77626960d738bd2c76d7e60fafd4354683a9458692780e3c88019a53160bcdf2705e4c632e185ae497ff2120e3a', 'Administrador', 'activo')
ON CONFLICT (usuario) DO NOTHING;

-- Categorías por defecto
INSERT INTO categoria (nombre, descripcion) VALUES 
('Medicamentos', 'Fármacos generales'),
('Cuidado Personal', 'Higiene y belleza'),
('Suplementos', 'Vitaminas y complementos')
ON CONFLICT DO NOTHING;

-- Presentaciones por defecto
INSERT INTO presentacion (nombre) VALUES 
('Unidad'),
('Caja'),
('Botella'),
('Blister')
ON CONFLICT DO NOTHING;

-- Proveedor de prueba
INSERT INTO proveedor (nombre, contacto, telefono) VALUES
('FarmaDistribuidora', 'Juan Pérez', '555-1234')
ON CONFLICT DO NOTHING;

-- Cliente Genérico
INSERT INTO cliente (nombre, apellidos, telefono) VALUES
('Cliente', 'General', '0000000')
ON CONFLICT DO NOTHING;
